


# Determine dispersal distances for larvae 

# Change depending on computer path
setwd("D:/Dropbox/PhD/Chapters/Recruitment over time")
setwd("C:/Users/james/Dropbox/PhD/Chapters/Recruitment over time")

base="C:/Users/james/Dropbox/PhD/Chapters"
base="D:/Dropbox/PhD/Chapters"
load(paste0(base,"/Environmental flows/riversspatialdata_final.RData"))
load(paste0(base,"/Recruitment over time/Multi year mate bonding in Murray cod/working environment all analysis of mating strategies incl between year repeat detections.RData"))


# Three files needed (generated by earlier code in C-5)
combined_fullsib_goulburn
combined_fullsib_barmah
combined_fullsib_chowilla
combined_fullsib

# But need to now add the lat/lon coordinates to the code 
# I extracted the details from the names in the PhD so there is no covariates code to connect them



covarfile <-read.csv("covariatesfilecombinedYOYandlarvaefamilieslarvae_length_wk_name_revised_stocked_lat2long2vari.csv")

covarfile <- subset(covarfile,covarfile$age=="larvae")
# Need to reformat the covar files name 


covarfile$new_name <- gsub("-", "",covarfile$new_name)
covarfile$new_name <- gsub("_", "",covarfile$new_name,fixed = TRUE)
View(covarfile)


combined_fullsib$Lat1 <- NA
combined_fullsib$Lat2 <- NA
combined_fullsib$Long1 <- NA
combined_fullsib$Long2 <- NA


# Note, a lot of the lats and longs are identical between each offspring in a dyad. This will lead to some errors in the dplyr pathways.

# Need to add a random value small enough to shift the samples by <1m but give variation




for (i in c(1:nrow(covarfile))) {
  j=1

  for (j in c(1:nrow(combined_fullsib))) {
    
    if (grepl(pattern = covarfile$new_name[i],x = combined_fullsib$OffspringID1[j])) {
      
      combined_fullsib$Lat1[j] <- covarfile$Lat2[i]
      combined_fullsib$Long1[j] <- covarfile$Long2[i]
      
    } 
    
    if (grepl(pattern = covarfile$new_name[i],x = combined_fullsib$OffspringID2[j])) {
      
      combined_fullsib$Lat2[j] <- covarfile$Lat2[i]
      combined_fullsib$Long2[j] <- covarfile$Long2[i]
      
    }
    
      }  
}

# Testing the pattern recognition grep works
if (grepl(pattern = covarfile$new_name[130],x = combined_fullsib$OffspringID1[1])) {
  
  combined_fullsib$Lat1[1] <- covarfile$lat[130]
  combined_fullsib$Long1[1] <- covarfile$lon[130]
  
} 



# Now that lat and long are added. I need to generate spatial dots for each 



library(riverdist)

library(dplyr)
library(purrr)
library(ggplot2)
library(ggrepel)
library(sf)
#library(USAboundaries)
library(Imap)


# First step. Convert X and Y values to spatial data. 
# Here is offspring 1 per sibling dyad

TargetindXYind1 <- as.data.frame(matrix(nrow=nrow(combined_fullsib), ncol = 2))
TargetindXYind1$ind <- combined_fullsib$OffspringID1
TargetindXYind1$Y <- combined_fullsib$Long1
TargetindXYind1$X <- combined_fullsib$Lat1
TargetindXYind1$pair <- seq(1,nrow(combined_fullsib), by =1)
TargetindXYind1 <- TargetindXYind1[, -c(1:2)]
colnames(TargetindXYind1) <- c("Ind","Lon","Lat", "pair")

TargetindXYind1 <- na.omit(TargetindXYind1)
TargetindXYind1geo <-st_as_sf(TargetindXYind1,coords = c("Lon", "Lat"),crs = 4326)
TargetindXYind1geo2 <- st_transform(TargetindXYind1geo, crs="+proj=longlat +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +no_defs")
#########

#here is offspring 2 per full sibling dyad

TargetindXYind2 <- as.data.frame(matrix(nrow=nrow(combined_fullsib), ncol = 2))
TargetindXYind2$ind <- combined_fullsib$OffspringID2
TargetindXYind2$Y <- combined_fullsib$Long2
TargetindXYind2$X <- combined_fullsib$Lat2
TargetindXYind2$pair <- seq(1,nrow(combined_fullsib), by =1)
TargetindXYind2 <- TargetindXYind2[, -c(1:2)]
colnames(TargetindXYind2) <- c("Ind","Lon","Lat", "pair")

TargetindXYind2 <- na.omit(TargetindXYind2)
TargetindXYind2geo <-st_as_sf(TargetindXYind2,coords = c("Lon", "Lat"),crs = 4326)
TargetindXYind2geo2 <- st_transform(TargetindXYind2geo, crs="+proj=longlat +ellps=WGS84 +towgs84=0,0,0,0,0,0,0 +no_defs")


library(tidyverse)
library(dplyr)

# Now we combine them into a super dataframe for the next steps to work

combinedtargets <- rbind(TargetindXYind1geo2,TargetindXYind2geo2)
# Here we 1. group the rows by a variable (pair, to indicate the dyads again), and cast the pairs of coords 
# from the two inds in the pair to generate a linestring (create a spatially defined line between point 1 and point 2 )
TargetindXYindlines <- combinedtargets %>% group_by(pair) %>% dplyr::summarize() %>% st_cast("LINESTRING")

# filter on distinct values to remove dups (which shouldn't exist now anyway because of the random variance given)
indXYmigratinggeo2linereduced <- distinct(TargetindXYindlines, geometry, .keep_all = TRUE)


# View it
plot(sitemapall$geometry)
plot(combinedtargets2both,add=T)
plot(indXYmigratinggeo2linereduced$geometry, add=T)

# generate points
ptns = st_cast(indXYmigratinggeo2linereduced, "POINT")
# there were a total of 6 duplicates
combinedtargets

combinedtargets <- combinedtargets[with(combinedtargets, order(pair)), ]

ptns
ptns$ind <- NA

# This code works!
# just make j the length of the points

# James note from Sep 2022. This works but it is very primitive. A more optimal solution would involve grep and regex based expressions and inserting it directly. This would 
# require exactly j length calculations which is 87,000 times faster.

# Feels a bit weird to call a stop through error when it is a success but it works
k=1 
j=1
for (i in 1:880000) {
  if(combinedtargets$pair[k]==ptns$pair[j]) {
    l=j+1
    m=k+1
    if(combinedtargets$pair[k]==ptns$pair[l] & combinedtargets$pair[k]==combinedtargets$pair[m]) {
      
      
      ptns$ind[j] <-combinedtargets$Ind[m]
      ptns$ind[l] <-combinedtargets$Ind[k]
      
      k=k+1
      j=1
    }
    
    else {
      
      j=j+1
      
    }
  }
  else {
    j=j+1
    
  }
  if(j==508) {
    
    j=1
    k=k+1
    
  }
  if(k==508) {
    stop("Finished running")
  }
}

# So this is the final for the non migrating ones.
View(ptns) 
fullsibs_pairwise_distancegeo <- ptns
#maxdistindXYnonmigratinggeo2linereduced10kmrange <- maxdistindXYnonmigratinggeo2linereduced


# Now project the results into the correct riverdist format (decimal)
fullsibs_pairwise_distancegeo_projected <- fullsibs_pairwise_distancegeo
fullsibs_pairwise_distancegeo_projected <- st_transform(fullsibs_pairwise_distancegeo, crs=3112)
fullsibs_pairwise_distancegeo_projected$X <- st_coordinates(fullsibs_pairwise_distancegeo_projected)[,1]
fullsibs_pairwise_distancegeo_projected$Y <- st_coordinates(fullsibs_pairwise_distancegeo_projected)[,2]


cdec_riv <- xy2segvert(x=fullsibs_pairwise_distancegeo_projected$X, y=fullsibs_pairwise_distancegeo_projected$Y, rivers=rivs_fixed)
head(cdec_riv)
hist(cdec_riv$snapdist, breaks=50,main="Point Snapping distance (CDEC to Flowline)", col="skyblue3", xlab="Snapping Distance (m)", family="Roboto Condensed")

migrating_river_inds_all_projected2 <- cbind(fullsibs_pairwise_distancegeo_projected, cdec_riv)


plot(x=rivs_fixed, color = FALSE)
points(migrating_river_inds_all_projected2$X, migrating_river_inds_all_projected2$Y, pch=16, col="red") # raw coords
riverpoints(seg=cdec_riv$seg, vert=cdec_riv$vert, rivers=rivs_fixed, pch=22, cex=1.0,
            bg="forestgreen") # snapped coords
text(migrating_river_inds_all_projected2$X, migrating_river_inds_all_projected2$Y, labels=migrating_river_inds_all_projected2$vert, pos = 4, family="Roboto Condensed")

# All data points have been snapped to a river, and are now analysable 
# Final steps. creating the pairs to analyse


migrating_river_inds_all_projected2

# note nrow= 2* number of pairs (can be anything above min though)
pairs <- as.data.frame(matrix(nrow=800, ncol=5))
i=1
j=2
for (q in (c(1:10000))) {
  
  if (migrating_river_inds_all_projected2$pair[i] == migrating_river_inds_all_projected2$pair[j])
  {
    startsegs <- migrating_river_inds_all_projected2$seg[i] 
    startverts <- migrating_river_inds_all_projected2$vert[i]
    endsegs <- migrating_river_inds_all_projected2$seg[j] 
    endverts <- migrating_river_inds_all_projected2$vert[j]
    
    
    pairnum <- migrating_river_inds_all_projected2$pair[i]
    
    
    distvalue <- riverdistance(startseg=startsegs, startvert=startverts, endseg=endsegs, endvert=endverts,
                               rivers=rivs_fixed, map=FALSE)
    
    pairs[i,1] <- migrating_river_inds_all_projected2$ind[i]
    pairs[i,2] <- migrating_river_inds_all_projected2$ind[j]
    pairs[i,3] <- pairnum
    pairs[i,4] <- distvalue
    pairs[i,5] <- (distvalue/1000)
    
    i=i+1
    j=i+1
  }
  else {
    i=i+1
    j=j+1 
    
  }
}
#


pairs <- na.omit(pairs)
colnames(pairs) <- c("Ind1","Ind2","Pairnum", "distscale", "dist_KM")
View(pairs)
par(mar = c(4, 4, 4, 4))

allindslarvaemovements <- pairs

# inds all is for all inds regardless of dispersal range
allindslarvaemovements






tiff("Within river distances half-siblings.tiff", units='cm', width =30,height=30, res=300)
ggplot(allindslarvaemovements, aes(x=dist_KM)) + 
  geom_histogram(color="black", fill="white", binwidth = 20)+
  labs(title="Distance travelled by half-siblings \n within rivers",x="Migration distance (km)", y = "Number of dyads")+
  theme_classic() +
  theme(plot.title =element_text(hjust=0.5,size=28)) +
  theme(axis.title.x =element_text(hjust=0.5,size=22)) +
  theme(axis.title.y =element_text(hjust=0.5,size=22)) +
  theme(axis.text = element_text(size = 18))

dev.off()




# Stats I want to add
# 1. the standard average standard deviation max min etc
# 2. how many inds caught in the same week were found in the same site/different sites. 
# 3. How many larvae sampled in different weeks found in the same site /different sites


mean(allindslarvaemovements$dist_KM)
# mean = 5.32km
sd(allindslarvaemovements$dist_KM)
# standard deviation =  15.55km
min(allindslarvaemovements$dist_KM)
# min = 0
max(allindslarvaemovements$dist_KM)
# max= 71.85km
sum((allindslarvaemovements$site1==allindslarvaemovements$site2))
sum(allindslarvaemovements$site1 != allindslarvaemovements$site2)



allindslarvaemovements$week1 <- NA
allindslarvaemovements$week2 <- NA

allindslarvaemovements$site1 <- NA
allindslarvaemovements$site2 <- NA


extr1 <- str_extract(allindslarvaemovements$Ind1[86],"[1-9][A-Z][A-Z]")
str_extract(extr1,"[A-Z].")
substring(text =allindslarvaemovements$Ind1[86],first = 5,last = 6 )

for (i in c(1:nrow(allindslarvaemovements))) {
  
  allindslarvaemovements$week1[i] <-str_extract(allindslarvaemovements$Ind1[i],"W.")
  allindslarvaemovements$week2[i] <-str_extract(allindslarvaemovements$Ind2[i],"W.")
  

  allindslarvaemovements$site1[i] <- substring(text =allindslarvaemovements$Ind1[i],first = 5,last = 6 )
  allindslarvaemovements$site2[i] <- substring(text =allindslarvaemovements$Ind2[i],first = 5,last = 6 )
  
  
}


larvae_sameweek <- subset(allindslarvaemovements,allindslarvaemovements$week1==allindslarvaemovements$week2)



mean(larvae_sameweek$dist_KM)
# mean = 5.42km
sd(larvae_sameweek$dist_KM)
# standard deviation =  15.55km
min(larvae_sameweek$dist_KM)
# min = 0
max(larvae_sameweek$dist_KM)
# max= 71.85km
sum((larvae_sameweek$site1==larvae_sameweek$site2))
sum(larvae_sameweek$site1 != larvae_sameweek$site2)

larvae_difweeks <- subset(allindslarvaemovements,allindslarvaemovements$week1!=allindslarvaemovements$week2)

mean(larvae_difweeks$dist_KM)
# mean = 5.42km
sd(larvae_difweeks$dist_KM)
# standard deviation =  15.55km
min(larvae_difweeks$dist_KM)
# min = 0
max(larvae_difweeks$dist_KM)
# max= 71.85km
sum((larvae_difweeks$site1==larvae_difweeks$site2))
sum(larvae_difweeks$site1 != larvae_difweeks$site2)


